services:
  web:
    build: ./project
    command: 
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.sh 
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:14
    volumes:
      - new_homesite_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - 5431:5432

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
    restart: unless-stopped
    depends_on:
      - db
  
  celery:
    build: ./project
    command: celery --app=config worker -l INFO
    env_file:
      - ./.env.dev
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - web

volumes:
  new_homesite_data_dev:
