version: '3.8'

services:
  web:
    image: keinermendoza/keinerdev:v1.1.0
    command:
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.prod.sh
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
    depends_on:
      - db
  
  celery:
    image: keinermendoza/keinerdev:v1.1.0
    command: celery --app=config worker -l INFO
    env_file:
      - ./.env.prod
    depends_on:
      - rabbitmq
      - web
    
  db:
    image: postgres:14
    volumes:
      - new_homesite_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  new_homesite_data_prod: