services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile.prod
    command: 
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.sh 
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:14
    volumes:
      - new_homesite_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - 5431:5432

  redis:
    image: redis:7-alpine
  
  celery:
    build:
      context: ./project
      dockerfile: Dockerfile.prod
    command: celery --app=config worker -l INFO
    volumes:
      - ./project:/usr/src/app
    env_file:
      - ./.env.dev
    restart: unless-stopped
    depends_on:
      - redis
      - web

volumes:
  new_homesite_data_dev:
