# Generated by Django 5.0.4 on 2024-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="topics",
            field=models.ManyToManyField(related_name="posts", to="blog.topic"),
        ),
    ]
