# Generated by Django 5.0.4 on 2024-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_post_created_post_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
