# Generated by Django 5.0.4 on 2024-06-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
    ]
