# Generated by Django 5.0.4 on 2024-07-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
