# Generated by Django 5.0.4 on 2024-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="resumen",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
