# Generated by Django 5.0.4 on 2024-07-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_post_resumen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="resumen",
        ),
    ]
