# Generated by Django 5.0.4 on 2024-07-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_remove_post_resumen"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="preview",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
