# Generated by Django 5.1 on 2025-03-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_postimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="post",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="PostImage",
        ),
    ]
