# Generated by Django 5.0.4 on 2024-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0003_alter_post_options_post_created_post_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("profession", models.CharField(max_length=80)),
                ("message", models.CharField(max_length=250)),
                ("image", models.FileField(upload_to="testimonials")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="core_testim_created_ee2c83_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(max_length=40)),
                ("customer_commercial_field", models.CharField(max_length=80)),
                ("description", models.TextField()),
                ("image", models.FileField(upload_to="projects")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "tecnologies",
                    models.ManyToManyField(related_name="projects", to="blog.topic"),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="core_projec_created_25e517_idx"
                    )
                ],
            },
        ),
    ]
