# Generated by Django 5.0.4 on 2024-06-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="status",
            field=models.CharField(
                choices=[("E", "Editing"), ("P", "Published")],
                default="E",
                max_length=1,
            ),
        ),
    ]
