# Generated by Django 5.0.4 on 2024-06-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_project_is_public_testimonial_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="status",
        ),
    ]
