# Generated by Django 5.0.4 on 2024-06-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_post_status"),
        ("core", "0007_remove_project_status_remove_testimonial_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tecnologies",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="blog.topic"
            ),
        ),
    ]
