# Generated by Django 5.0.6 on 2024-06-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_projectimage_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
