# Generated by Django 5.0.4 on 2024-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_project_video_demo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
