# Generated by Django 5.1 on 2025-03-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_project_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tecnologies",
        ),
    ]
