# Generated by Django 5.1 on 2025-02-16 17:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wg_blog", "0002_blogpost_excerpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", 0), ("github_gist", 2)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL del Gist de GitHub"},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("url", 1)]], {}),
                },
            ),
        ),
    ]
