# Generated by Django 5.1 on 2025-02-23 13:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wg_blog", "0004_alter_blogpost_body_alter_blogpost_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_Text", 0), ("quotes", 1), ("mensaje", 4), ("code", 7)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Información"),
                                ("warning", "Advertencia"),
                                ("error", "Error"),
                                ("success", "Éxito"),
                            ],
                            "label": "Tipo de alerta",
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Texto que aparecerá en la alerta.",
                            "label": "Mensaje",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("tipo", 2), ("mensaje", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("python", "Python"),
                                ("javascript", "JavaScript"),
                                ("html", "HTML"),
                                ("css", "CSS"),
                                ("bash", "Bash"),
                                ("sql", "SQL"),
                                ("django", "Django Template"),
                                ("react", "React"),
                            ],
                            "label": "Language",
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Escribe o pega tu código aquí.",
                            "label": "Code",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 5), ("code", 6)]],
                        {},
                    ),
                },
            ),
        ),
    ]
